language: node_js
node_js:
  - stable
branches:
  only:
    - master
cache:
  directories:
    - node_modules
sudo: required

services:
  - docker

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
after_script:
  - docker build -t nathanqueija/portfolio .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push nathanqueija/portfolio
